version: '3.5'
services:
  db:
    build: postgresql
    image: flats_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - flats_ntwrk
  pgadmin:
    build: pgadmin
    image: flats_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - flats_ntwrk
  swagger-ui:
    build: swagger-ui
    image: flats_swagger-ui:1.0.2
    ports:
      - "81:8080"
    networks:
      - flats_ntwrk

  proxy:
    build: proxy
    image: flats_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - flats_ntwrk
networks:
    flats_ntwrk:
      name: flats_ntwrk