spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  profiles:
    default: local
app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy