spring:
  email:
    message:
      link: |
        or follow to the URL 
        http://localhost:80/api/v1/users/verification?code=
      mail: |
        &mail=
      code: |
        Verification code:

server:
  port: 8081