spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=users
    password: 4712vs5988gh
    username: postgres

app:
  user:
    storage: MEMORY #MEMORY or JDBC

server:
  port: 8084