spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service?currentSchema=users
    password: 4712vs5988gh
    username: postgres

app:
    jwt:
      secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
      issuer: ITAcademy

user:
  storage: MEMORY #MEMORY or JDBC

server:
  port: 8084