spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/user_service?currentSchema=users
    password: postgres
    username: postgres

server:
  port: 8080

app:
  feign:
    audit-logs:
      url: http://audit-service:8084

mail:
  service:
    url: http://mail-service:8081/mail