spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  profiles:
    default: test

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: ITAcademy
  feign:
    audit-logs:
      url: http://localhost:8084