spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  profiles:
      default: local
app:
  url:
    base-sale: https://re.kufar.by/l/minsk/kupit/kvartiru
    base-rent: https://re.kufar.by/l/minsk/snyat/kvartiru-dolgosrochno