spring:
  datasource:
    driver-class-name: org.postgresql.Driver

app:
  url:
    base-sale: https://re.kufar.by/l/minsk/kupit/kvartiru
    base-rent: https://re.kufar.by/l/minsk/snyat/kvartiru-dolgosrochno